version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_DB: marvel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
